### ISSUE TITLE
Import syslog fails on Windows

### ISSUE THREAD

**Issue by mathershifter** [arista-eosplus/pyeapi#10]
Installation fails on Windows. It looks like its only referenced in utils.py.  Can this be ignored in Windows and just print to the screen?

```posh
PS C:\> pip install pyeapi
Collecting pyeapi
  Using cached pyeapi-0.2.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "c:\users\v-jesmat\appdata\local\temp\pip-build-es44ei\pyeapi\setup.py", line 37, in <module>
        from pyeapi import __version__, __author__
      File "pyeapi\__init__.py", line 36, in <module>
        from .client import load_config, connect, connect_to, config_for
      File "pyeapi\client.py", line 97, in <module>
        from pyeapi.utils import load_module, make_iterable
      File "pyeapi\utils.py", line 35, in <module>
        import syslog
    ImportError: No module named syslog
```

**Comment by privateip** [comment]
Yeah this can be ignored.  It was added for troubleshooting onbox applications.  I just added hotfix-0.2.3 branch.  Can you do a pip install from that branch source and confirm there are no additional issues?  Once confirmed, I will merge back into master and develop and upload to PyPi

**Comment by mathershifter** [comment]
Install works now. Thank you!
