### ISSUE TITLE
Exception when parsing IP MTU for port-channel if it isn't configured

### ISSUE THREAD

**Issue by privateip** [arista-eosplus/pyeapi#11]
```
Ethernet3/1 is up, line protocol is up (connected)
  Hardware is Ethernet, address is 001c.735e.e0c7 (bia 001c.735e.e0c7)
  Member of Port-Channel1000
  Ethernet MTU 9214 bytes , BW 10000000 kbit
  Full-duplex, 10Gb/s, auto negotiation: off, uni-link: unknown
  Up 3 days, 23 hours, 57 minutes, 59 seconds
  Loopback Mode : None
  3 link status changes since last clear
  Last clearing of "show interface" counters never
  5 minutes input rate 274 bps (0.0% with framing overhead), 0 packets/sec
  5 minutes output rate 1.49 kbps (0.0% with framing overhead), 0 packets/sec
     357698 packets input, 353333582 bytes
     Received 0 broadcasts, 24021 multicast
     0 runts, 0 giants
     0 input errors, 0 CRC, 0 alignment, 0 symbol, 0 input discards
     0 PAUSE input
     331371 packets output, 413482277 bytes
     Sent 10 broadcasts, 150079 multicast
     0 output errors, 0 collisions
     0 late collision, 0 deferred, 0 output discards
     0 PAUSE output


Script Exec :

My name is Ethernet3/1
Traceback (most recent call last):
  File "eapi1", line 5, in <module>
    vlans.getall()
  File "/Library/Python/2.7/site-packages/pyeapi/api/ipinterfaces.py", line 117, in getall
    interface = self.get(name)
  File "/Library/Python/2.7/site-packages/pyeapi/api/ipinterfaces.py", line 94, in get
    resp['mtu'] = int(MTU_RE.search(config, re.M).group('value'))
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by advornic** [comment]
resp['mtu'] = int(MTU_RE.search(config, re.M).group('value') <b> or 0</b>)

is one quick fix.

**Comment by eosplus** [comment]
Wrong - please ignore.
