### ISSUE TITLE
Question: `timeout` option when running bash commands via the API

### ISSUE THREAD

**Issue by mirceaulinic** [arista-eosplus/pyeapi#128]
Hello,

I have just a quick question regarding the execution of bash commands through the API:

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "napalm_eos/eos.py", line 1219, in traceroute
    [command], encoding='text')[0].get('output')
  File "/home/mircea/napalm/local/lib/python2.7/site-packages/pyeapi/client.py", line 672, in run_commands
    response = self._connection.execute(commands, encoding)
  File "/home/mircea/napalm/local/lib/python2.7/site-packages/pyeapi/eapilib.py", line 475, in execute
    response = self.send(request)
  File "/home/mircea/napalm/local/lib/python2.7/site-packages/pyeapi/eapilib.py", line 396, in send
    raise CommandError(code, msg, command_error=err, output=out)
pyeapi.eapilib.CommandError: Error [1004]: CLI command 2 of 2 'bash traceroute 8.8.8.8  -m 255 -w 2' failed: incompatible command [Command not permitted via API access. To run a bash command over the Command API,  use the 'timeout  <seconds>' option.]
```

I am not sure how to send the `timeout` option?

Thank you,
Mircea

**Comment by phil-dileo** [comment]
It's as simple as:

```
bash timeout <time> <command>
```

eg
```
bash timeout 5 date
```

**Comment by mirceaulinic** [comment]
Hi @phil-dileo - thanks for looking into this!


I thought I had to send them as separate commands..

```python
commands = [
            'bash timeout 60',
            'bash traceroute 8.8.8.8  -m 255 -w 2'
]
```

Thanks!
