### ISSUE TITLE
When excepting "pyeapi.eapilib.ConnectionError" I still get the pyeapi script spewing socket.timeout to the screen

### ISSUE THREAD

**Issue by shimamizu** [arista-eosplus/pyeapi#229]
Traceback (most recent call last):
  File "/home/shimamizu/.pyenv/versions/3.9.11/lib/python3.9/site-packages/pyeapi/eapilib.py", line 447, in send
    response_content = response.read()
  File "/home/shimamizu/.pyenv/versions/3.9.11/lib/python3.9/http/client.py", line 470, in read
    return self._readall_chunked()
  File "/home/shimamizu/.pyenv/versions/3.9.11/lib/python3.9/http/client.py", line 577, in _readall_chunked
    chunk_left = self._get_chunk_left()
  File "/home/shimamizu/.pyenv/versions/3.9.11/lib/python3.9/http/client.py", line 560, in _get_chunk_left
    chunk_left = self._read_next_chunk_size()
  File "/home/shimamizu/.pyenv/versions/3.9.11/lib/python3.9/http/client.py", line 520, in _read_next_chunk_size
    line = self.fp.readline(_MAXLINE + 1)
  File "/home/shimamizu/.pyenv/versions/3.9.11/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/home/shimamizu/.pyenv/versions/3.9.11/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/home/shimamizu/.pyenv/versions/3.9.11/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out
Error connecting to the eAPI for {my_hostname}

The last line is proof that my exception did catch it:
except pyeapi.eapilib.ConnectionError as conn_error:
            print(f"Error connecting to the eAPI for {self.switch_hostname}")

I have also tried adding an exception for socket.timeout in my pyeapi script wrapper, but that never catches it, since the socket.timeout portion of the error appears to be happening inside the pyeapi library, not handling well, and then just passing the pyeapi.eapilib.ConnectionError back to me which I am able to catch. 

In my logging file I then just see: 
self.logger.warning(
                f"Connection error on {self.switch_hostname}:\n {str(conn_error.message)}"
            )

2022-06-27 12:03:25,739 WARNING  Connection error on {my_hostname}:
 Socket error during eAPI connection: The read operation timed out

That second line I assume been the error that the pyeapi sent back about socket.timeout

I would like all the barfing from socket.timeout not to print on screen when I'm catching pyeapi.eapilib.ConnectionError correctly

**Comment by dlyssenk** [comment]
Hi @shimamizu, how do trigger both tracebacks exactly? I'd need to replicate it in order to dig the issue.

**Comment by shimamizu** [comment]
@dlyssenk are you on the networktocode slack? If so ping me on there and I can send more details. Username is shima there. Or shoot me your Arista email and I’ll start an email thread :)

**Comment by dlyssenko** [comment]
> @dlyssenk are you on the networktocode slack? If so ping me on there and I can send more details. Username is shima there. Or shoot me your Arista email and I’ll start an email thread :)

Sorry, I did not notice I was logged under my personal github account, here's a correct one.

**Comment by dlyssenko** [comment]
- the exception is clearly interceptable (as per the  outputs), the reason for seeing that traceback is in `eapilib` module: once it intercepts the socket level exception the way it handles it is first by _logging the traceback_.

So, the work-around to suppress printing the traceback is to set the logging level to a more severe level.

Here’s how you could do this:
```
import logging
...
        try:
            log_level = pyeapi.eapilib._LOGGER.getEffectiveLevel()            
            pyeapi.eapilib._LOGGER.setLevel( logging.CRITICAL )
            if run_method == "run_commands":
                command_output = self.node.run_commands(command)[0]
            ...
        except ...:
        ...
        finally:
            pyeapi.eapilib._LOGGER.setLevel( log_level )  
```
- that way you should not see those tracebacks.

I won't be changing the current behavior - the socket level errors are deemed critical enough to have a traceback printed, plus there’s a work-around to suppress it, as shown above. 

let me know if any questions

**Comment by shimamizu** [comment]
I will test this out next week!
