### ISSUE TITLE
[API] users - can't create password with non-alpha/int characters

### ISSUE THREAD

**Issue by phil-arista** [arista-eosplus/pyeapi#23]
According to the EOS configuration guide

"
Valid usernames begin with A-Z, a-z, or 0-9 and may also contain any of these characters:
@#$%^&*()-_= +{}[];<>,.~|
"

But when you try to do that in pyeapi:

```
>>> node = pyeapi.connect_to('veos_test_01')
>>> users = node.api('users')
>>> users.getall()
{'admin': {'privilege': '1', 'nopassword': False, 'secret': '$1$g2dMhkqJ$WjdvCWpil3tXDWHXu.nmD1', 'role': 'network-admin', 'format': '5'}}
>>> 
>>> users.create_with_nopassword('a@#$%^&*()-_=+{}[];<>,.~|')
False
```

**Comment by phil-arista** [comment]
Here's the traceback from an ansible-eos testcase:

```
======================================================================
ERROR: Test[eos_user]: Create user with name that has uncommon characters
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/phil/.virtualenvs/ansible/lib/python2.7/site-packages/nose/case.py", line 267, in setUp
    try_run(self.test, names)
  File "/Users/phil/.virtualenvs/ansible/lib/python2.7/site-packages/nose/util.py", line 471, in try_run
    return func()
  File "/Users/phil/eos-plus/ansible/ansible-eos/test/test_module.py", line 102, in setUp
    self.node.config(self.testcase.setup)
  File "/Users/phil/eos-plus/pyeapi/pyeapi/client.py", line 508, in config
    response = self.run_commands(commands)
  File "/Users/phil/eos-plus/pyeapi/pyeapi/client.py", line 631, in run_commands
    response = self._connection.execute(commands, encoding)
  File "/Users/phil/eos-plus/pyeapi/pyeapi/eapilib.py", line 464, in execute
    response = self.send(request)
  File "/Users/phil/eos-plus/pyeapi/pyeapi/eapilib.py", line 385, in send
    raise CommandError(code, msg, command_error=err, output=out)
CommandError: CLI command 3 of 3 'no username a@#$%^&*()-_=+{}[];<>,.~|' failed: invalid command
-------------------- >> begin captured stdout << ---------------------
>> Running setup commands
>> ['no username a@#$%^&*()-_=+{}[];<>,.~|']
CLI command 3 of 3 'no username a@#$%^&*()-_=+{}[];<>,.~|' failed: invalid command
['no username a@#$%^&*()-_=+{}[];<>,.~|']

--------------------- >> end captured stdout << ----------------------
-------------------- >> begin captured logging << --------------------
pyeapi.eapilib: DEBUG: Request content: {"params": {"format": "json", "version": 1, "cmds": ["enable", "configure", "no username a@#$%^&*()-_=+{}[];<>,.~|"]}, "jsonrpc": "2.0", "method": "runCmds", "id": "4343561424"}
pyeapi.eapilib: DEBUG: Response: status: 200, reason: OK
pyeapi.eapilib: DEBUG: Response content: {"jsonrpc": "2.0", "id": "4343561424", "error": {"data": [{}, {}, {"errors": ["Invalid input (at token 2: 'a@#$%^&*()-_=+{}[];<>,.~|')"]}], "message": "CLI command 3 of 3 'no username a@#$%^&*()-_=+{}[];<>,.~|' failed: invalid command", "code": 1002}}
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
```

**Comment by phil-arista** [comment]
Tested in the CLI:
```
localhost(config)#username a@#$ nopassword
localhost(config)#username a@#$% nopassword
localhost(config)#username a@#$%^ nopassword
localhost(config)#username a@#$%^& nopassword
localhost(config)#username a@#$%^&* nopassword
localhost(config)#username a@#$%^&*( nopassword
% Invalid input
```

Looks like the documentation might be misleading.

**Comment by phil-arista** [comment]
This is a documentation issue.  The characters (){}[] cannot be part of the username name attribute.

**Comment by phil-arista** [comment]
Release Note:
The characters ``(){}[]`` cannot be part of a username. Documentation has been updated to reflect this.
