### ISSUE TITLE
Unable to request "show agent qtrace" via pyeapi, getting "no space left on device"

### ISSUE THREAD

**Issue by shimamizu** [arista-eosplus/pyeapi#233]
You have to request text encoding for this command, as it won't work with json encoding. streaming=True option doesn't help as that function only works for commands with json outputs. Device actually has plenty of free space. My only guess is that perhaps it's a buffering issue? Can we enable streaming=true for text encoding if that might fix this issue? 

```>>> test1 = eapi.node.enable("show agent qtrace", encoding="text")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/shimamizu/.pyenv/versions/3.9.11/lib/python3.9/site-packages/pyeapi/client.py", line 712, in enable
    resp = self.run_commands(command, encoding, send_enable,
  File "/home/shimamizu/.pyenv/versions/3.9.11/lib/python3.9/site-packages/pyeapi/client.py", line 771, in run_commands
    response = self._connection.execute(commands, encoding, **kwargs)
  File "/home/shimamizu/.pyenv/versions/3.9.11/lib/python3.9/site-packages/pyeapi/eapilib.py", line 554, in execute
    response = self.send(request)
  File "/home/shimamizu/.pyenv/versions/3.9.11/lib/python3.9/site-packages/pyeapi/eapilib.py", line 473, in send
    raise CommandError(code, msg, command_error=err, output=out)
pyeapi.eapilib.CommandError: Error [-32603]: [Errno 28] No space left on device```

If you try to enable streaming=True we see it doesn't work for text encoding

```>>> eapi.node.enable("show agent qtrace", encoding="text", streaming=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/shimamizu/.pyenv/versions/3.9.11/lib/python3.9/site-packages/pyeapi/client.py", line 712, in enable
    resp = self.run_commands(command, encoding, send_enable,
  File "/home/shimamizu/.pyenv/versions/3.9.11/lib/python3.9/site-packages/pyeapi/client.py", line 775, in run_commands
    response['result'].pop(0)
IndexError: pop from empty list```

Plenty of space on the device.

```my-example-switch#bash df -lh
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda1        28G  2.6G   25G  10% /mnt/flash
none            4.8G  479M  4.3G  10% /
none            4.8G  479M  4.3G  10% /.overlay
/dev/loop0      802M  802M     0 100% /rootfs-i386
devtmpfs        8.0M     0  8.0M   0% /dev
tmpfs            16G     0   16G   0% /dev/shm
tmpfs            16G  968K   16G   1% /run
tmpfs            16G     0   16G   0% /sys/fs/cgroup
tmpfs           4.8G   16K  4.8G   1% /tmp
tmpfs            64M  772K   64M   2% /.deltas
tmpfs            64M  772K   64M   2% /var/run
tmpfs            16G     0   16G   0% /var/run/netns
tmpfs            16G     0   16G   0% /.deltas/var/run/netns
tmpfs            64M  772K   64M   2% /var/tmp
tmpfs           3.2G     0  3.2G   0% /var/core
tmpfs           3.2G  136M  3.1G   5% /var/log
tmpfs           7.9G   83M  7.8G   2% /var/shmem
tmpfs            24G     0   24G   0% /var/shmem/stashes
/dev/sda2        61M  1.3M   59M   3% /mnt/crash```

**Comment by dlyssenko** [comment]
You're right, `streaming` is an optional parameter for `json.dumps` call, thus it's not applicable (won't work) with the `text` output format.

When you observe `'no space left on device'` - it indeed means that undergoing operation has run out of space to build the output, and the problem with some outputs like `show agent qtrace` is indeed those are not jsonized and they could be enormously big (thus, no matter how much we could possible increase the mount size, there will be instances when `show agent qtrace` would still hit the limit). E.g., on my dut, `show agent qtrace` takes ~762MB unzipped and around 62MB zipped.

So, I propose you to handle it the following way:
1. initially try it directly with eapi command intercepting the  `CommandError` exception. 
2. If the latter is raised, then you try handling it like you already did - first execute the command redirecting the output onto the flash (`show agent qtrace >flash:qtrace.log`, or using `gzip`) and then (scp) transfer the file (programmatically) from `flah:` onto your host, where you run the script, and handle it locally.

**Comment by dlyssenko** [comment]
Given the described caveat is attributed to eapi rather than to pyeapi framework, plus given a work-around, I'm closing the issue.
