### ISSUE TITLE
ImportError: No module named cmdline when trying to make unittest

### ISSUE THREAD

**Issue by dathelen** [arista-eosplus/pyeapi#69]
I am sure I am missing something obvious here, but whenever I try to make unittest i see the following:

dt at tacteam in ~/code/pyeapi on deb2579 [!]
$ make unittest
Cleaning up distutils stuff
rm -rf build
rm -rf dist
rm -rf MANIFEST
rm -rf *.egg-info
Cleaning up byte compiled python stuff
find . -type f -regex ".*\.py[co]$" -delete
coverage run -m unittest discover test/unit -v
Traceback (most recent call last):
  File "/usr/bin/coverage", line 9, in <module>
    load_entry_point('coverage==4.0.3', 'console_scripts', 'coverage')()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 378, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2566, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2260, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
ImportError: No module named cmdline

make: *** [unittest] Error 1

I am pretty certain the pip install -r dev-requirements completed successfully:

dt at tacteam in ~/code/pyeapi on deb2579 [!]
$ sudo pip install -r dev-requirements.txt
Requirement already satisfied (use --upgrade to upgrade): netaddr in /usr/lib/python2.7/site-packages (from -r dev-requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): mock in /usr/lib/python2.7/site-packages (from -r dev-requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): coveralls in /usr/lib/python2.7/site-packages (from -r dev-requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): twine in /usr/lib/python2.7/site-packages (from -r dev-requirements.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): check-manifest in /usr/lib/python2.7/site-packages (from -r dev-requirements.txt (line 5))
Requirement already satisfied (use --upgrade to upgrade): pep8 in /usr/lib/python2.7/site-packages (from -r dev-requirements.txt (line 6))
Requirement already satisfied (use --upgrade to upgrade): pyflakes in /usr/lib/python2.7/site-packages (from -r dev-requirements.txt (line 7))
Requirement already satisfied (use --upgrade to upgrade): coverage in /usr/lib64/python2.7/site-packages (from -r dev-requirements.txt (line 8))
Requirement already satisfied (use --upgrade to upgrade): sphinx in /usr/lib64/python2.7/site-packages (from -r dev-requirements.txt (line 9))
Requirement already satisfied (use --upgrade to upgrade): sphinxcontrib-napoleon in /usr/lib/python2.7/site-packages (from -r dev-requirements.txt (line 10))
Requirement already satisfied (use --upgrade to upgrade): flake8 in /usr/lib/python2.7/site-packages (from -r dev-requirements.txt (line 11))
Requirement already satisfied (use --upgrade to upgrade): flake8-print in /usr/lib/python2.7/site-packages (from -r dev-requirements.txt (line 12))
Requirement already satisfied (use --upgrade to upgrade): flake8-debugger in /usr/lib/python2.7/site-packages (from -r dev-requirements.txt (line 13))
Requirement already satisfied (use --upgrade to upgrade): pep8-naming in /usr/lib

**Comment by dathelen** [comment]
ok, this looks to be an issue with an odd python install on a lab box.  Sorry for the noise
