### ISSUE TITLE
AttributeError: 'module' object has no attribute 'connect'

### ISSUE THREAD

**Issue by ronaldpetty** [arista-eosplus/pyeapi#96]
`sudo pip install pyeapi`

I assume I have missed a step, any thoughts what is causing this?  I can provide more info, but not sure what would be needed.

user@ubuntu:~$ python
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyeapi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyeapi.py", line 3, in <module>
    connection = pyeapi.connect(host='10.2.0.5')
AttributeError: 'module' object has no attribute 'connect'

Regards.

**Comment by phil-dileo** [comment]
We're all guilty of that!
